### ISSUE TITLE
Add event property identifying the version of the proxy

### ISSUE THREAD

**Issue by Jocumsen** [navikt/amplitude-proxy#20]
The proxy should add a property identifying the running version of the proxy to all collected events before they are forwarded. 

Needs:
- Support potential debugging when there is error with the data in Amplitude.
- The version number will also function as a "watermark" confirming that data in Amplitude has been properly collected using the Proxy (and not through direct collection from app to Amplitude).

**Comment by mijohansen** [comment]
We are collecting this from APP_VERSION... app_version need to be changed to include git commit date.

**Comment by Jocumsen** [comment]
Flyttet til Trello.
