### ISSUE TITLE
Add whitelisting of applications

### ISSUE THREAD

**Issue by Jocumsen** [navikt/amplitude-proxy#21]
To reduce the risk of receiving spam from unauthorized applications, our apps should consider mechanisms for including a server side generated token allowing the proxy to verify the legitimacy of the client application.

Note: This is a theoretical problem identified in the risk analysis. The consequence is polluted data (loss of data value and accuracy), and not risk of privacy concerns. The issue is low priority until we can confirm that this is an actual problem.

**Comment by mortenlj** [comment]
This might be a valid use case for using HTTP signing, following this IETF RFC Draft: https://tools.ietf.org/html/draft-cavage-http-signatures-12

**Comment by Jocumsen** [comment]
Flyttet til Trello.
