### ISSUE TITLE
Sette opp tilstrekkelig CD-pipeline med Github Actions

### ISSUE THREAD

**Issue by Jocumsen** [navikt/amplitude-proxy#32]
- Trunk based development?
- Hvordan deploye og teste i preprod/gcp-dev?
- Hvordan sikre at prod = master for å trygt kunne hotpatche uten å risikere å dra med endringer andre tester i preprod?
- Annet?

Jeg foreslår at utviklerne våre diskuterer og bestemmer hvordan vi skal praktisere dette for proxyen (ideelt sett på tilsvarende måte som for våre andre applikasjoner/tjenester).

**Comment by JeremiahUy** [comment]
forslag: for hver push i master så deployeres det til preprod, og kun når vi lager en github release vil det deployeres til prod

**Comment by mortenlj** [comment]
Jeg foretrekker trunk based development, med feature toggles og roll forward.

Hvis man skal teste en feature som er under utvikling så er det bedre å bruke feature toggles for dette enn å deploye forskjellig applikasjon til testmiljøer. Ideelt sett så ønsker man at testmiljøer er så like prod som mulig, slik at man kan reprodusere eventuelle feil i testmiljøet. Da er det lite hensiktsmessig at testmiljøet kjører en annen applikasjon.

Tilsvarende så er det ofte enklere å fikse en feil ved å "rulle forover" enn å rulle tilbake, fordi man da slipper å rulle tilbake andre endringer som har blitt gjort på master i mellomtiden.

Jeg syns en CD-pipeline funker best hvis man kan deploye til et testmiljø, kjøre noen automatiske tester som gir deg en god indikasjon på at ting virker som det skal, og så automatisk deploye til prod når testene er grønne. Jeg har jobbet så lenge i en slik setting at jeg glemmer å deploye til prod de gangene jeg er borti en pipeline som krever manuell godkjenning for prodsetting 🤷‍♂ .

**Comment by Jocumsen** [comment]
Vi flytter det som gjenstår her inn i Trello-boardet:
- Sette opp automatisk deployment til prod dersom automatiske tester lykkes i preprod
